# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install package
      run: |
        python -m pip install --upgrade pip build
        python -m pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Ruff
      run: ruff check --format=github .
    - name: Check with black
      run: black --check --verbose ./src
    - name: Test with pytest
      run: pytest
